services:
  - type: web
    name: relay-wms-backend-fixed
    env: node
    plan: free
    buildCommand: "cd src && npm install --prefix .."
    startCommand: "node src/server.js"
    rootDir: .
    autoDeploy: true
