services:
  - type: web
    name: relay-wms-backend
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    root: .
    envVars:
      - key: NODE_ENV
        value: production
