services:
  - type: web
    name: relay-wms-backend-fixed
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node ./src/src/server.js"
    rootDir: .
    autoDeploy: true
